<?php

namespace Estina\Bundle\HomeBundle\Entity;

/**
 * TalkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalkRepository extends \Doctrine\ORM\EntityRepository
{
}
