<?php

namespace Estina\Bundle\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TalkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalkRepository extends EntityRepository
{
    public function findActiveTalks()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->select('t')
            ->from('Estina\Bundle\HomeBundle\Entity\Talk', 't')
            ->where('t.active = 1')
            ->orderBy('t.createdOn', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
