<?php

namespace Estina\Bundle\HomeBundle\Entity;

/**
 * TrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTalkTracks()
    {
        return $this->findTracksByType(Track::TYPE_TALK);
    }

    public function findWorkshopTracks()
    {
        return $this->findTracksByType(Track::TYPE_WORKSHOP);
    }

    public function findTracksByType($type)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->select('t')
            ->from('Estina\Bundle\HomeBundle\Entity\Track', 't')
            ->where('t.type = :type')
            ->setParameter('type', $type)
            ->orderBy('t.position', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findTracks()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->select('t')
            ->from('Estina\Bundle\HomeBundle\Entity\Track', 't')
            ->orderBy('t.position', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
